document.getElementById('sidebar').innerHTML =
 "<ul><li><a href='index.html'>概览</a></li>"
 + "<li><a href='ports.html'>端口配置</a></li>"
 + "<li><a href='stat.html'>端口统计</a></li>"
 + "<li><a href='vlan.html'>VLAN 配置</a></li>"
 + "<li><a href='l2.html'>L2 转发表</a></li>"
 + "<li><a href='mirror.html'>端口镜像</a></li>"
 + "<li><a href='lag.html'>链路聚合</a></li>"
 + "<li><a href='eee.html'>EEE 节能以太网</a></li>"
 + "<li><a href='bandwidth.html'>带宽限制</a></li>"
 + "<li><a href='system.html'>系统设置</a></li>"
 + "<li><a href='update.html'>固件升级</a></li></ul>";
